---
clusterName: homeofficedb

clusterUsers:
  - name: homeofficeuser
    databases:
      - homeofficedb

dbInitSQL: |-
  \c homeofficedb;
  DROP SCHEMA IF EXISTS homeoffice;
  CREATE SCHEMA homeoffice;
  DROP SCHEMA IF EXISTS coffeeshop;
  CREATE SCHEMA coffeeshop;
  DROP SCHEMA IF EXISTS coffeeshop-backend;
  CREATE SCHEMA coffeeshop-backend;
