clusterGroup:
  name: hub
  isHubCluster: true
  # Note: setting this to true stores the vault unseal keys inside a cluster secret and
  # is fundamentally insecure
  insecureUnsealVaultInsideCluster: true

  namespaces:
  - open-cluster-management
  - vault
  - golang-external-secrets
  - coffeeshop-homeoffice

  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.5
      csv: advanced-cluster-management.v2.5.0

    amqstreams-ho:
      name: amq-streams
      namespace: openshift-operators
      channel: amq-streams-2.x
      csv: amqstreams.v2.0.1-0

    crunchypgo-ho:
      name: postgresoperator
      namespace: openshift-operators
      channel: v5
      csv: postgresoperator.v5.1.2

  projects:
  - hub

  applications:
    acm:
      name: acm
      namespace: open-cluster-management
      project: hub
      path: common/acm
      ignoreDifferences:
      - group: internal.open-cluster-management.io
        kind: ManagedClusterInfo
        jsonPointers:
          - /spec/loggingCA

    vault:
      name: vault
      namespace: vault
      project: hub
      path: common/hashicorp-vault

    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      path: common/golang-external-secrets

    coffeeshopdb-homeoffice:
      name: golang-external-secrets
      namespace: coffeeshop-homeoffice
      project: hub
      path: charts/hub/coffeeshopdb-homeoffice

  imperative:
    # NOTE: We *must* use lists and not hashes. As hashes lose ordering once parsed by helm
    # The default schedule is every 10 minutes: imperative.schedule
    # Total timeout of all jobs is 1h: imperative.activeDeadlineSeconds
    # imagePullPolicy is set to always: imperative.imagePullPolicy
    # For additional overrides that apply to the jobs, please refer to
    # https://hybrid-cloud-patterns.io/imperative-actions/#additional-job-customizations
    jobs: []
    #- name: noop
      # ansible playbook to be run
    #  playbook: ansible/playbooks/noop.yml
      # per playbook timeout in seconds
   #   timeout: 234
      # verbosity: "-v"

#  managedClusterGroups:
#    region-one:
#      name: region-one
#      helmOverrides:
#      - name: clusterGroup.isHubCluster
#        value: false
#      clusterSelector:
#        matchLabels:
#          clusterGroup: region-one

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#    pipelines:
#      name: pipelines
#      namespace: production
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: stable
#      overrides:
#      - name: myparam
#        value: myparam
#
#    pipelines_staging:
#    - name: pipelines
#      namespace: staging
#      project: datacenter
#      path: applications/pipeline
#      repoURL: https://github.com/you/applications.git
#      targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#    vendor-app:
#      name: vendor-app
#      namespace: default
#      project: vendor
#      path: path/to/myapp
#      repoURL: https://github.com/vendor/applications.git
#      targetRevision: main

#  managedSites:
#    factory:
#      name: factory
#      # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#      targetRevision: main
#      path: applications/factory
#      helmOverrides:
#      - name: site.isHubCluster
#        value: false
#      clusterSelector:
#        matchExpressions:
#        - key: vendor
#          operator: In
#          values:
#            - OpenShift
