# This playbook fetches the managed cluster's CAbundle from ACM's objects
# and puts it in a secret inside the imperative namespace. One secret per cluster
---
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    ns: imperative
  tasks: []
