---
apiVersion: v1
kind: Route
metadata:
  name: quarkuscoffeeshop-web
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: quarkuscoffeeshop-web
---
apiVersion: v1
kind: Route
metadata:
  name: quarkuscoffeeshop-customermocker
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: quarkuscoffeeshop-customermocker

