apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.clusterName }}
spec:
  users: {{ .Values.clusterUsers | toPrettyJson }}
  databaseInitSQL:
    key: {{ .Values.dbInitConfigMap.key }}
    name: {{ .Values.dbInitConfigMap.name }}
  postgresVersion: {{ .Values.postgresVersion }}
  instances: {{ .Values.clusterInstances | toPrettyJson }}
{{- if .Values.enablePgAdmin }}
  userInterface:
    pgAdmin: {{ .Values.pgAdmin | toPrettyJson }}
{{- end }}
  backups:
    pgbackrest: {{ .Values.pgbackrest | toPrettyJson }}
