---
{{- if .Values.enablePgAdmin }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.clusterName }}-pgadmin
spec:
  port:
    targetPort: pgadmin
  to:
    kind: Service
    name: {{ .Values.clusterName }}-pgadmin
{{- end }}
